title: "The Interurbanist: What's Happening at the SHAG Interurban"
description: "SHAG Interurban's Information Clearinghouse"
url: "https://www.theinterurbanist.org"
baseurl: ""
timezone: "America/Los_Angeles"

# Using page bundles: each story is a folder with index.md plus its media.
defaults:
  - scope: { path: "tales" }
    values: { layout: entry, section: tales }
  - scope: { path: "events" }
    values: { layout: entry, section: events }
  - scope: { path: "management" }
    values: { layout: entry, section: management }
  - scope: { path: "lostnfound" }
    values: { layout: entry, section: lostnfound }
  - scope: { path: "safety" }
    values: { layout: entry, section: safety }
  - scope: { path: "style" }
    values: { layout: entry, section: style }
  - scope: { path: "visions" }
    values: { layout: entry, section: visions }

exclude:
  - _local

logo: /assets/img/the_interurbanist_flag_1411x294.jpg

twitter:
  card: summary_large_image   # bigger preview cards when possible

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

permalink: pretty
