title: The Interurbanist
description: SHAG Interurban's Information Clearinghouse
url: https://wildjo.github.io
baseurl: /theinterurbanist
timezone: America/Los_Angeles
plugins:
- jekyll-feed
- jekyll-seo-tag
collections:
  longform:
    output: true
    permalink: /tales/:title/
  shortform:
    output: true
    permalink: /notes/:title/
feed:
  collections:
  - longform
  - shortform
defaults:
- scope:
    path: ''
    type: longform
  values:
    layout: entry
    section: tales
- scope:
    path: ''
    type: shortform
  values:
    layout: entry
    section: notes
- scope:
    path: pages
  values:
    layout: page
markdown: kramdown
kramdown:
  input: GFM
