title: "The Interurbanist: What's Happening at the SHAG Interurban"
description: "SHAG Interurban's Information Clearinghouse"
url: "https://www.theinterurbanist.org"
baseurl: ""
timezone: "America/Los_Angeles"

# Using page bundles: each story is a folder with index.md plus its media.
defaults:
  - scope: { path: "tales" }
    values: { layout: entry, section: tales }
  - scope: { path: "notes" }
    values: { layout: entry, section: notes }

exclude:
  - _local

logo: /assets/img/the_interurbanist_flag_1411x294.jpg

twitter:
  card: summary_large_image   # bigger preview cards when possible

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

permalink: pretty
