title: "The Interurbanist: What's Happening at the SHAG Interurban"
description: "SHAG Interurban's Information Clearinghouse"
url: "https://www.theinterurbanist.org"
baseurl: ""
timezone: "America/Los_Angeles"


# Using page bundles: each story is a folder with index.md plus its media.
defaults:
  - scope: { path: "tales" }
    values: { layout: entry, section: tales }
  - scope: { path: "events" }
    values: { layout: entry, section: events }
  - scope: { path: "management" }
    values: { layout: entry, section: management }
  - scope: { path: "lostnfound" }
    values: { layout: entry, section: lostnfound }
  - scope: { path: "safety" }
    values: { layout: entry, section: safety }
  - scope: { path: "style" }
    values: { layout: entry, section: style }
  - scope: { path: "visions" }
    values: { layout: entry, section: visions }

# Canonical section definitions (single source of truth)
sections:
  - slug: tales
    label: "Tales from the Independent"
  - slug: events
    label: "Events Notice"
    sort:
      key: starts_at
      direction: asc
    card:
      date_format: "%b %-d, %Y • %l:%M %P"
      date_field: starts_at
      default_format: "%b %-d, %Y"
      show_location: true
    entry:
      date_format: "%b %-d, %Y • %l:%M %P"
      date_field: starts_at
  - slug: management
    label: "From the Management"
  - slug: lostnfound
    label: "Lost & Found"
  - slug: safety
    label: "Safety Tips for Long Lives"
  - slug: style
    label: "Style & Grace"
  - slug: visions
    label: "Visions of Independent Living"
    entry:
      date_format: "%b %-d, %Y • %l:%M %P"

placeholders:
  card: /assets/placeholders/placeholder_card_400x300.png

date_formats:
  card_default: "%b %-d, %Y"
  entry_default: "%b %-d, %Y"

exclude:
  - _local
  - vendor

logo: /assets/img/the_interurbanist_flag_1411x294.jpg

twitter:
  card: summary_large_image   # bigger preview cards when possible

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

permalink: pretty
