title: "The Interurbanist: What's Happening at the SHAG Interurban"
description: "SHAG Interurban's Information Clearinghouse"
url: "https://wildjo.github.io"
baseurl: "/theinterurbanist"
timezone: "America/Los_Angeles"

# Using page bundles: each story is a folder with index.md plus its media.
defaults:
  - scope: { path: "tales" }
    values: { layout: entry, section: tales }
  - scope: { path: "notes" }
    values: { layout: entry, section: notes }

exclude:
  - _local

plugins:
  - jekyll-seo-tag

permalink: pretty
